development:
  adapter: postgresql
  encoding: unicode
  database: demo_app_development
  pool: 5
  username: ptv1
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: demo_app_test
  pool: 5
  username: ptv1
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: demo_app
  pool: 5
  username: ptv1
  password:
  host: localhost
